### ISSUE TITLE
Wrong return `background-image: url(http://`

### ISSUE THREAD

**Issue by hzlzh** [maltsev/posthtml-attrs-parser#1]
**In**
`<span style="background-image: url(http://temp.im/100x100);" class="listview__thumb-img"></span>`
**Out**
`{ 'background-image': 'url(http' }`

When we use `var attrs = parseAttrs(node.attrs);` it returns wrong output:

**Comment by maltsev** [comment]
@hzlzh thank you for the bug report. I'll fix it today.

**Comment by hzlzh** [comment]
@maltsev cheers~

**Comment by maltsev** [comment]
Done: [0.1.1](https://github.com/maltsev/posthtml-attrs-parser/releases/tag/0.1.1)
